### PR TITLE
refs #67 Thumbor 7.0.0a5

### PR DESCRIPTION
**Pull request by gingerlime**
* updated Dockerfile and docker-entrypoint based on
  https://github.com/MinimalCompact/thumbor/issues/67#issuecomment-592918001
* updated push, so we will push alpha tags on this branch, but not
  overwriting `latest` (and also semaphore CI)
* using thumbor's built-in multiprocess

TODO

* [x] [circus / multiprocess is broken](https://github.com/MinimalCompact/thumbor/issues/67#issuecomment-592954554)
* [ ] move dependencies to `requirements.txt` ?
* [ ] add more libraries (which?)
* [ ] is the conf file backwards compatible?

### CODE REVIEW

**Comment by gingerlime** [comment]
pushed `minimalcompact/thumbor:thumbor-7a5` tag to docker hub

**Comment by demosdemon** [comment]
thanks for this, the 7.0.0 alpha image doesn't include the `tc` extras like `tc_aws`

**Comment by gingerlime** [comment]
Thanks @demosdemon. Yes, it's on the list, but would appreciate any help during this process. So PRs or any other contribution is welcome.

**Comment by demosdemon** [comment]
Update:

I have a version of Thumbor 7 with unreleased versions of [`circus`](https://github.com/circus-tent/circus/pull/1129) and [`tc_aws`](https://github.com/thumbor-community/aws/pull/142) [here](https://github.com/MinimalCompact/thumbor/compare/master...demosdemon:master). I hate git pinning, so this should not be used yet. I also tweaked the build script so I could easily build, tag, and upload under my namespace. 

I also pulled Boost out into its own image. The Debian provided Boost uses different python header versions than the docker image (3.6 vs 3.8) which will eventually cause surprising and hard to diagnose issues. Doing this also allowed me to create a handy script to generate pinned requirements.txt using pip-tools. There was a reason why I pinned `remotecv < 3`, but I can't remember what it was now.

I also added some magic taken from the [Docker python](https://github.com/docker-library/python/blob/master/3.8/buster/slim/Dockerfile) image to slim the apt dependencies after it's built. I've reduced the image size by 50%! This needs to be further tested to make sure any truly needed dependencies aren't falsely removed (I've already encountered a few).

I'll be cleaning this up over the weekend and will probably rebase/squash on top of your alpha branch. Let me know if you have any comments or questions?

**Comment by gingerlime** [comment]
Thanks for the update @demosdemon ! Sounds like you did some serious digging into it 👍 

A few notes from my side:

* circus is no longer needed and was removed. Thumbor 7 supports multiprocess internally so there's no longer a need for it
* reducing the size of the image sounds nice, but not a priority/objective for this project in my opinion. Thumbor is server software, and pretty stable overall. Pulling/pushing images can take a few seconds more or less, it doesn't make a huge difference. Stability/predictability is much more important. So I personally prefer to go with something safer that won't surprise us

Otherwise all sounds pretty great!

**Comment by gingerlime** [comment]
I need some help figuring out the updates to `requirements.txt` ... Is [this](https://github.com/MinimalCompact/thumbor/compare/master...demosdemon:master#diff-bca5a8409bc679ae96d0c43c8b7624623518d1ba7cfc0d815e91d3d5fa1459f7) a safe option to use? I notice that it has a couple of non-stable pointers to git (e.g. `tc_aws`)... 

How can we align/sync all the 3rd-party modules with thumbor 7 ?

Currently this PR [only loads thumbor 7.0.0a5](https://github.com/MinimalCompact/thumbor/pull/76/files#diff-3a19b07bd74c26c14ca5687b8068813c8836eee6834c591b0f9fa94cb82cdfbcL33-L35) without any other python modules, which obviously won't be that useful for users... Yet, I'm not sure which versions of 3rd party modules to use, hopefully still achieving backwards compatibility so if someone upgrades the docker image, (most) all dependencies are there...

@kkopachev @demosdemon @heynemann are you able to help here?

**Comment by heynemann** [comment]
Working on it...

**Comment by gingerlime** [comment]
let's continue on #103

**Pull request closed without merging**
