### PR TITLE
Fix build installing opencv from pip. Fix pillow-simd builds too

### LINKED ISSUE #36: build error: ln: failed to access '/usr/lib/python2.7/dist-packages/cv.py': No such file or directory
```
docker build --pull -f thumbor/Dockerfile -t minimalcompact/thumbor thumbor/
Sending build context to Docker daemon  38.91kB
Step 1/23 : FROM python:2
2: Pulling from library/python
Digest: sha256:7a61a96567a2b2ba5db636c83ffa18db584da4024fa5839665e330934cb6b2b2
Status: Image is up to date for python:2
 ---> 3edf9092825f
Step 2/23 : LABEL maintainer="MinimalCompact"
 ---> Using cache
 ---> 6c8f4cd1cc0f
Step 3/23 : VOLUME /data
 ---> Using cache
 ---> 98b66887d338
Step 4/23 : RUN      awk '$1 ~ "^deb" { $3 = $3 "-backports"; print; exit }' /etc/apt/sources.list > /etc/apt/sources.list.d/backports.list &&     apt-get update &&     apt-get -y upgrade &&     apt-get -y autoremove &&     apt-get install -y -q         python-numpy         python-opencv         git         curl         libdc1394-22         libjpeg-turbo-progs         graphicsmagick         libgraphicsmagick++3         libgraphicsmagick++1-dev         libgraphicsmagick-q16-3         zlib1g-dev         libboost-python-dev         libmemcached-dev         gifsicle         ffmpeg &&     apt-get clean
 ---> Using cache
 ---> 0e68b558e994
Step 5/23 : ENV HOME /app
 ---> Using cache
 ---> 2e0a42b2cb06
Step 6/23 : ENV SHELL bash
 ---> Using cache
 ---> 1c18e46b1ec2
Step 7/23 : ENV WORKON_HOME /app
 ---> Using cache
 ---> 4c25fcf19ad6
Step 8/23 : WORKDIR /app
 ---> Using cache
 ---> c6f962ff18e1
Step 9/23 : COPY requirements.txt /app/requirements.txt
 ---> Using cache
 ---> 27bf042e7ad0
Step 10/23 : RUN pip install --trusted-host None --no-cache-dir    -r /app/requirements.txt
 ---> Using cache
 ---> 0dbb39bed9d3
Step 11/23 : COPY conf/thumbor.conf.tpl /app/thumbor.conf.tpl
 ---> Using cache
 ---> a8d675bd7394
Step 12/23 : ADD conf/circus.ini.tpl /etc/
 ---> Using cache
 ---> 084d8a9ac513
Step 13/23 : RUN mkdir  /etc/circus.d /etc/setup.d
 ---> Using cache
 ---> 37efd7ee4cb7
Step 14/23 : ADD conf/thumbor-circus.ini.tpl /etc/circus.d/
 ---> Using cache
 ---> 75c59aff1cdb
Step 15/23 : RUN     ln /usr/lib/python2.7/dist-packages/cv2.x86_64-linux-gnu.so /usr/local/lib/python2.7/cv2.so &&     ln /usr/lib/python2.7/dist-packages/cv.py /usr/local/lib/python2.7/cv.py
 ---> Running in be730558ceaf
ln: failed to access '/usr/lib/python2.7/dist-packages/cv.py': No such file or directory
The command '/bin/sh -c ln /usr/lib/python2.7/dist-packages/cv2.x86_64-linux-gnu.so /usr/local/lib/python2.7/cv2.so &&     ln /usr/lib/python2.7/dist-packages/cv.py /usr/local/lib/python2.7/cv.py' returned a non-zero code: 1
```

### PR DESCRIPTION
**Pull request by kkopachev**
Fixes #36 

I think that would do it.

I am not sure we need to install all these extra packages like `graphicsmagick`, but that is another story.

### CODE REVIEW

**Comment by gingerlime** [comment]
That's awesome @kkopachev ! Thank you.

I'm definitely in favour of removing anything that's not strictly necessary, and moving things to pip definitely makes sense as well. Most parts of the Dockerfile were things I "collected" from other projects and somehow made work, but it's not something I built from scratch or have a thorough understanding of. That's where your help is invaluable!

I tried to build it however and had an error...

```
Step 16/20 : RUN if [ -z "$SIMD_LEVEL" ]; then       CC="cc" && PILLOW_PACKET="pillow" && PILLOW_VERSION_SUFFIX="" ;    else       CC="cc -m$SIMD_LEVEL" && PILLOW_PACKET="pillow-SIMD" && PILLOW_VERSION_SUFFIX=".post99" ;    fi ;     PILLOW_VERSION=$(python -c 'import PIL; print(PIL.__version__)') &&     pip uninstall -y pillow || true &&     LIB=/usr/lib/x86_64-linux-gnu/     INCLUDE=/usr/include/x86_64-linux-gnu/     pip install --no-cache-dir -U --force-reinstall --no-binary=:all: "${PILLOW_PACKET}<=${PILLOW_VERSION}${PILLOW_VERSION_SUFFIX}"     --global-option="build_ext" --global-option="--enable-lcms"     --global-option="build_ext" --global-option="--enable-zlib"     --global-option="build_ext" --global-option="--enable-jpeg"     --global-option="build_ext" --global-option="--enable-tiff"
 ---> Running in da9421b17295
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Uninstalling Pillow-5.1.0:
  Successfully uninstalled Pillow-5.1.0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
/usr/local/lib/python2.7/site-packages/pip/_internal/commands/install.py:244: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting pillow-SIMD<=5.1.0.post99
  Downloading https://files.pythonhosted.org/packages/4b/0a/e10fd8512e10f245700f9b177889eba5cfd0dace8fd2d10955eea19c3b7c/Pillow-SIMD-4.3.0.post0.tar.gz (13.8MB)
Collecting olefile (from pillow-SIMD<=5.1.0.post99)
  Downloading https://files.pythonhosted.org/packages/34/81/e1ac43c6b45b4c5f8d9352396a14144bba52c8fec72a80f425f6a4d653ad/olefile-0.46.zip (112kB)
Skipping bdist_wheel for pillow-SIMD, due to binaries being disabled for it.
Skipping bdist_wheel for olefile, due to binaries being disabled for it.
Installing collected packages: olefile, pillow-SIMD
  Running setup.py install for olefile: started
    Running setup.py install for olefile: finished with status 'error'
    ERROR: Complete output from command /usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-SzlgyS/olefile/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext --enable-lcms build_ext --enable-zlib build_ext --enable-jpeg build_ext --enable-tiff install --record /tmp/pip-record-PI6cyh/install-record.txt --single-version-externally-managed --compile:
    ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --enable-lcms not recognized
    ----------------------------------------
ERROR: Command "/usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-SzlgyS/olefile/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext --enable-lcms build_ext --enable-zlib build_ext --enable-jpeg build_ext --enable-tiff install --record /tmp/pip-record-PI6cyh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-SzlgyS/olefile/
WARNING: You are using pip version 19.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c if [ -z "$SIMD_LEVEL" ]; then       CC="cc" && PILLOW_PACKET="pillow" && PILLOW_VERSION_SUFFIX="" ;    else       CC="cc -m$SIMD_LEVEL" && PILLOW_PACKET="pillow-SIMD" && PILLOW_VERSION_SUFFIX=".post99" ;    fi ;     PILLOW_VERSION=$(python -c 'import PIL; print(PIL.__version__)') &&     pip uninstall -y pillow || true &&     LIB=/usr/lib/x86_64-linux-gnu/     INCLUDE=/usr/include/x86_64-linux-gnu/     pip install --no-cache-dir -U --force-reinstall --no-binary=:all: "${PILLOW_PACKET}<=${PILLOW_VERSION}${PILLOW_VERSION_SUFFIX}"     --global-option="build_ext" --global-option="--enable-lcms"     --global-option="build_ext" --global-option="--enable-zlib"     --global-option="build_ext" --global-option="--enable-jpeg"     --global-option="build_ext" --global-option="--enable-tiff"' returned a non-zero code: 1
```

I'll try to update Semaphore, so it can do builds for PRs automatically, so it's easier to inspect what's going on.

**Comment by gingerlime** [comment]
You can now see the [build on Semaphore](https://minicompact.semaphoreci.com/workflows/3723fd93-0400-4f9f-9578-c599f88d7086).

I guess we can remove `--enable-lcms`? https://github.com/thumbor/thumbor/issues/1102#issuecomment-452203339 :)

**Comment by kkopachev** [comment]
well.. this is all coming from `remotecv` package restricting pillow version to `<5.2.0`, so pip installs `5.1.0`. In case of SIMD container, we try to install pillow-simd with less than or equal version of already installed pillow: <=5.1.0. It happens that first available version of pillow-simd is 4.3.0 which probably has different build system and different flags.

**Comment by gingerlime** [comment]
Ah, I see. I think I was able to use a later version before though... (will have to check or look at old build logs if I can find any)

**Comment by kkopachev** [comment]
it's `remotecv` package https://github.com/thumbor/remotecv/blob/2.2.2/setup.py#L58

**Comment by gingerlime** [comment]
Sorry @kkopachev it's pretty late for me and my brain is working :) I'm still trying to understand ... how did it work before though? (the remotecv restriction was there before, right?).

In any case, I can see that the build works now, so let's merge this 👍

**Comment by kkopachev** [comment]
It was hardcoded to 5.2.0 previously. Not ideal, but works.

**Pull request merged**
