### PR TITLE
refactor tests to run after parallel builds

### PR DESCRIPTION
**Pull request by gingerlime**

### CODE REVIEW

**Comment by gingerlime** [comment]
@danquack I need your help on this one. I'm trying to figure out a "flow" for the CI/CD pipeline. We want to build the images, run tests, and if the tests pass, push to the registry (once merged). I tried something using artifacts, but it's pretty slow, and also not sure if/how it plays with multiarch builds. Any thoughts/suggestions?

**Comment by mpdude** [comment]
Do you really need multi-job parallelism, or would a single job do that builds all images, runs tests and pushes the images when they all pass?

**Comment by mpdude** [comment]
Maybe the ghcr.io is a better way to share build layers/cache instead of using artifacts

**Comment by gingerlime** [comment]
Good thinking @mpdude on both points. I was still hoping we can parallelize some stuff, but it's not super-critical. Also just nice to separate jobs logically than a slightly-hairy ball that the build/push scripts were. I anyway want to move things to ghcr, but maybe later? (also want to figure out how to move the old images from docker hub)

**Comment by mpdude** [comment]
Regarding old images, you should be able to pull-and-push from/to Docker Hub/GitHub. But maybe Thumbor 7 is a good opportunity to cut over?

Parallelism is nice, but when it means we have to e.g. setup QEMU repeatedly or push GBs of temporary images into a registry, just to pull them again in a fresh worker for the next job, maybe we don’t gain much 🌱

**Comment by danquack** [comment]
Github has this notion of [needs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds), which allows for sequential processing (tests before push). Does that accomplish what you want?

**Comment by danquack** [comment]
It sounds like you may have a use case for both parallelism and sequential nature?

**Pull request merged**
